name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: personoids
          password: ${{ secrets.DOCKER_HUB_TOKEN }}          
    - uses: actions/checkout@v3    
    - name: Build and push Base
      uses: docker/build-push-action@v4.0.0
      with:
          context: .
          file: ./Dockerfile-base
          tags: personoids/plugin-base:latest
          push: true
    - name: Build and push chroma
      uses: docker/build-push-action@v4.0.0
      with:
          context: .
          file: ./Dockerfile-chroma
          tags: personoids/chroma:latest
          push: true          
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: personoids/plugin-lite
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}    
    - name: Build and push plugin
      uses: docker/build-push-action@v4.0.0
      with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}  
          push: true
